import React, { useState, useMemo, useEffect } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, StyleSheet, ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import {
  useFonts,
  SpaceGrotesk_400Regular,
  SpaceGrotesk_500Medium,
  SpaceGrotesk_600SemiBold,
  SpaceGrotesk_700Bold,
} from '@expo-google-fonts/space-grotesk';
import { translateTranscript, diarizeTranscript } from '../lib/groq';

const C = {
  bg:    '#f2f3f5',
  white: '#ffffff',
  dark:  '#202020',
  lime:  '#c9f158',
  gray:  '#888888',
  muted: '#bbbbbe',
  red:   '#e57373',
  warn:  '#fff8e1',
  warnB: '#f59e0b',
};

const statusColor = (s) => ({ processed: '#166534', error: '#c0392b', pending: '#7a5c00' }[s] || C.gray);
const statusBg    = (s) => ({ processed: '#dcfce7',  error: '#fee2e2',  pending: '#fef9c3' }[s] || C.bg);
const statusLabel = (s) => ({ processed: 'Done',      error: 'Error',    pending: 'Pending' }[s] || s || 'Pending');

const fmt = (iso) => {
  if (!iso) return '';
  return new Date(iso).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
};

export default function SessionDetailScreen({ route, navigation }) {
  const [fontsLoaded] = useFonts({
    SpaceGrotesk_400Regular,
    SpaceGrotesk_500Medium,
    SpaceGrotesk_600SemiBold,
    SpaceGrotesk_700Bold,
  });
  const [downloading, setDownloading] = useState(false);

  const { session, isPatient } = route.params;
  const d = session.extracted_data || session.processed_data || {};

  const downloadPrescription = async () => {
    setDownloading(true);
    try {
      const patName  = session.patient_name || d.patient_name || 'Patient';
      const date     = fmt(session.created_at);
      const diag     = d.diagnosis || 'Consultation';
      const medsRows = medications.map(med => `
        <tr>
          <td>${med.prescription_name || med.name || '-'}</td>
          <td>${med.dose_mg ? med.dose_mg + ' mg' : med.dosage || '-'}</td>
          <td>${med.frequency || '-'}</td>
          <td>${med.duration || '-'}</td>
        </tr>`).join('');
      const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; color: #202020; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 30px; border-bottom: 2px solid #c9f158; padding-bottom: 20px; }
    .clinic h1 { margin: 0; font-size: 24px; color: #202020; }
    .clinic p  { margin: 4px 0; font-size: 13px; color: #888; }
    .rx-badge  { background: #c9f158; color: #202020; font-size: 36px; font-weight: bold; padding: 10px 20px; border-radius: 10px; }
    .patient-box { background: #f2f3f5; border-radius: 12px; padding: 16px 20px; margin-bottom: 24px; display: flex; gap: 40px; }
    .patient-box span { font-size: 12px; color: #888; display: block; margin-bottom: 4px; }
    .patient-box strong { font-size: 15px; }
    .diagnosis { font-size: 14px; margin-bottom: 24px; }
    .diagnosis span { color: #888; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #202020; color: #fff; padding: 10px 14px; text-align: left; font-size: 12px; }
    td { padding: 10px 14px; font-size: 13px; border-bottom: 1px solid #eee; }
    tr:nth-child(even) td { background: #f9f9f9; }
    .footer { margin-top: 40px; font-size: 12px; color: #bbb; text-align: center; border-top: 1px solid #eee; padding-top: 16px; }
    .sig { margin-top: 30px; text-align: right; }
    .sig strong { font-size: 14px; }
    .sig p { font-size: 11px; color: #888; margin: 2px 0; }
  </style>
</head>
<body>
  <div class="header">
    <div class="clinic">
      <h1>Prana Health</h1>
      <p>AI-Assisted Prescription</p>
    </div>
    <div class="rx-badge">Rx</div>
  </div>
  <div class="patient-box">
    <div><span>Patient Name</span><strong>${patName}</strong></div>
    <div><span>Patient ID</span><strong>${session.patient_id || '-'}</strong></div>
    <div><span>Date</span><strong>${date}</strong></div>
  </div>
  <div class="diagnosis"><span>Diagnosis: </span>${diag}</div>
  <table>
    <thead><tr><th>Medication</th><th>Dose</th><th>Frequency</th><th>Duration</th></tr></thead>
    <tbody>${medsRows}</tbody>
  </table>
  <div class="sig">
    <strong>____________________________</strong>
    <p>Authorised Signature</p>
    <p>Generated by Prana · ${date}</p>
  </div>
  <div class="footer">This prescription was AI-assisted. Please verify with your doctor before dispensing.</div>
</body>
</html>`;
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Prescription',
          UTI: 'com.adobe.pdf',
        });
      } else {
        await Print.printAsync({ uri });
      }
    } catch (e) {
      console.warn('prescription error', e.message);
    } finally {
      setDownloading(false);
    }
  };

  const symptoms    = d.symptoms     || [];
  const medications = d.medications  || [];
  const missing     = d.missing_info || [];
  const vitals      = d.vitals       || {};

  if (!fontsLoaded) return null;

  return (
    <SafeAreaView style={s.container} edges={['top', 'bottom']}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}>

        {/* BACK */}
        <TouchableOpacity style={s.backBtn} onPress={() => navigation.goBack()} activeOpacity={0.7}>
          <Ionicons name="arrow-back-outline" size={18} color={C.dark} />
          <Text style={s.backText}>Back</Text>
        </TouchableOpacity>

        {/* TITLE ROW */}
        <View style={s.titleRow}>
          <Text style={s.pageTitle}>Session Detail</Text>
          <View style={s.titleBadges}>
            {d.follow_up_required ? (
              <View style={[s.statusBadge, { backgroundColor: '#fee2e2' }]}>
                <Ionicons name="calendar-outline" size={12} color="#b91c1c" />
                <Text style={[s.statusText, { color: '#b91c1c' }]}>Follow-up</Text>
              </View>
            ) : (
              <View style={[s.statusBadge, { backgroundColor: statusBg(session.status) }]}>
                <Text style={[s.statusText, { color: statusColor(session.status) }]}>{statusLabel(session.status)}</Text>
              </View>
            )}
          </View>
        </View>

        {/* META */}
        <View style={s.metaRow}>
          <Ionicons name="calendar-outline" size={14} color={C.muted} />
          <Text style={s.metaText}>{fmt(session.created_at)}</Text>
          {(session.detected_language || session.language) && (
            <>
              <Text style={s.metaDot}>·</Text>
              <Text style={s.metaText}>{(session.detected_language || session.language).toUpperCase()}</Text>
            </>
          )}
          {session.duration_seconds && (
            <>
              <Text style={s.metaDot}>·</Text>
              <Text style={s.metaText}>{Math.round(session.duration_seconds)} sec</Text>
            </>
          )}
        </View>

        {/* SUMMARY CARD */}
        {d.summary && (
          <View style={s.summaryCard}>
            <Text style={s.summaryText}>{d.summary}</Text>
          </View>
        )}

        {/* PATIENT + SEVERITY */}
        {(session.patient_name || d.patient_name) && (
          <InfoRow icon="person-outline" label="Patient" value={session.patient_name || d.patient_name} />
        )}
        {session.patient_id && (
          <InfoRow icon="card-outline" label="Patient ID" value={session.patient_id} />
        )}
        {d.severity && (
          <InfoRow
            icon="pulse-outline"
            label="Severity"
            value={d.severity.toUpperCase()}
            valueColor={d.severity === 'severe' ? C.red : d.severity === 'moderate' ? '#c09a1a' : '#3a6e00'}
          />
        )}

        {/* SYMPTOMS */}
        {symptoms.length > 0 && (
          <Section icon="thermometer-outline" title="Symptoms">
            <View style={s.chipWrap}>
              {symptoms.map((sym, i) => (
                <View key={i} style={s.chip}><Text style={s.chipText}>{sym}</Text></View>
              ))}
            </View>
          </Section>
        )}

        {/* DURATION */}
        {d.symptom_duration && (
          <InfoRow icon="hourglass-outline" label="Duration" value={d.symptom_duration} />
        )}

        {/* DIAGNOSIS */}
        {d.diagnosis && (
          <InfoRow icon="medkit-outline" label="Diagnosis" value={d.diagnosis} bold />
        )}

        {/* MEDICATIONS */}
        {medications.length > 0 && (
          <Section icon="flask-outline" title="Medications">
            {medications.map((med, i) => (
              <View key={i} style={s.medCard}>
                <View style={s.medNameRow}>
                  <Ionicons name="ellipse" size={6} color={C.dark} style={{ marginTop: 6 }} />
                  <View style={{ flex: 1 }}>
                    <Text style={s.medNameText}>
                      {med.prescription_name && med.prescription_name !== med.name
                        ? `${med.prescription_name} (${med.name})`
                        : med.name}
                    </Text>
                    <View style={s.medPillRow}>
                      {(med.dose_mg || med.dosage) && (
                        <View style={s.medPill}>
                          <Ionicons name="resize-outline" size={10} color={C.gray} />
                          <Text style={s.medPillText}>
                            {med.dose_mg ? `${med.dose_mg} mg` : med.dosage}
                          </Text>
                        </View>
                      )}
                      {med.frequency && (
                        <View style={s.medPill}>
                          <Ionicons name="time-outline" size={10} color={C.gray} />
                          <Text style={s.medPillText}>{med.frequency}</Text>
                        </View>
                      )}
                      {med.duration && (
                        <View style={s.medPill}>
                          <Ionicons name="calendar-outline" size={10} color={C.gray} />
                          <Text style={s.medPillText}>{med.duration}</Text>
                        </View>
                      )}
                    </View>
                  </View>
                </View>
              </View>
            ))}
          </Section>
        )}

        {/* VITALS */}
        {Object.values(vitals).some(Boolean) && (
          <Section icon="heart-outline" title="Vitals">
            <View style={s.vitalsGrid}>
              {vitals.bp    && <VitalTile label="Blood Pressure" value={vitals.bp}    icon="fitness-outline"   />}
              {vitals.temp  && <VitalTile label="Temperature"    value={vitals.temp}  icon="thermometer-outline" />}
              {vitals.pulse && <VitalTile label="Pulse"          value={vitals.pulse} icon="pulse-outline"     />}
              {vitals.spo2  && <VitalTile label="SpO₂"           value={vitals.spo2}  icon="water-outline"     />}
            </View>
          </Section>
        )}

        {/* ALLERGIES */}
        {(d.allergies || []).length > 0 && (
          <Section icon="alert-circle-outline" title="Allergies">
            <View style={s.chipWrap}>
              {d.allergies.map((a, i) => (
                <View key={i} style={[s.chip, { backgroundColor: '#fce8e6' }]}>
                  <Text style={[s.chipText, { color: '#c0392b' }]}>{a}</Text>
                </View>
              ))}
            </View>
          </Section>
        )}

        {/* FOLLOW UP */}
        {d.follow_up && (
          <InfoRow icon="calendar-outline" label="Follow-up" value={d.follow_up} />
        )}

        {/* PRESCRIPTION DOWNLOAD — patient only */}
        {medications.length > 0 && isPatient && (
          <TouchableOpacity
            style={s.rxBtn}
            onPress={downloadPrescription}
            activeOpacity={0.82}
            disabled={downloading}
          >
            <View style={s.rxBtnInner}>
              {downloading
                ? <ActivityIndicator color={C.dark} size="small" />
                : <Ionicons name="download-outline" size={20} color={C.dark} />
              }
              <View>
                <Text style={s.rxBtnTitle}>{downloading ? 'Generating…' : 'Download Prescription'}</Text>
                <Text style={s.rxBtnSub}>PDF · Show at pharmacy</Text>
              </View>
            </View>
            <Ionicons name="chevron-forward" size={18} color={C.dark} />
          </TouchableOpacity>
        )}

        {/* TRANSCRIPT */}
        {(session.corrected_transcript || session.raw_transcript) && (
          <TranscriptChat session={session} />
        )}

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

// ── Sub-components ────────────────────────────────────────────────────────────
function Section({ icon, title, children }) {
  return (
    <View style={s.sectionCard}>
      <View style={s.sectionHeader}>
        <Ionicons name={icon} size={15} color={C.gray} />
        <Text style={s.sectionTitle}>{title}</Text>
      </View>
      {children}
    </View>
  );
}

function InfoRow({ icon, label, value, bold, valueColor }) {
  return (
    <View style={s.infoRow}>
      <Ionicons name={icon} size={16} color={C.muted} style={{ width: 24 }} />
      <Text style={s.infoLabel}>{label}</Text>
      <Text style={[s.infoValue, bold && { fontFamily: 'SpaceGrotesk_700Bold' }, valueColor && { color: valueColor }]}>
        {value}
      </Text>
    </View>
  );
}

function VitalTile({ label, value, icon }) {
  return (
    <View style={s.vitalTile}>
      <Ionicons name={icon} size={18} color={C.gray} />
      <Text style={s.vitalValue}>{value}</Text>
      <Text style={s.vitalLabel}>{label}</Text>
    </View>
  );
}

// ── Transcript helpers ──────────────────────────────────────────────────────
function parseLines(text) {
  if (!text?.trim()) return null;
  const lines = text.split('\n').map(l => l.trim()).filter(Boolean);
  const parsed = lines.map(line => {
    const m = line.match(/^([^:]{1,40}):\s+(.+)/);
    if (m) return { name: m[1].trim(), text: m[2].trim() };
    return { name: null, text: line };
  });
  const named = parsed.filter(l => l.name !== null).length;
  if (named < Math.max(1, Math.ceil(parsed.length * 0.4))) return null;
  return parsed;
}

function TranscriptChat({ session }) {
  const text = session.corrected_transcript || session.raw_transcript;
  const detectedLang = (session.detected_language || session.language || 'en')
    .replace('-IN', '').toLowerCase();

  const [selectedLang,   setSelectedLang]   = useState('original');
  const [translating,    setTranslating]    = useState(false);
  const [cache,          setCache]          = useState({});
  const [diarized,       setDiarized]       = useState(null);  // [{speaker,name,text}] after auto-diarize
  const [diarizing,      setDiarizing]      = useState(false);

  // Try to parse speaker labels already baked into corrected_transcript
  const storedLines = useMemo(() => parseLines(text), [text]);

  // On mount: if no stored labels, auto-diarize the raw transcript via LLM
  useEffect(() => {
    if (storedLines) return; // already labeled — skip
    if (!text?.trim() || text.length < 60) return; // too short to diarize
    const doctorName  = session.extracted_data?.doctor_name  || 'Doctor';
    const patientName = session.patient_name || session.extracted_data?.patient_name || 'Patient';
    setDiarizing(true);
    diarizeTranscript(text, doctorName, patientName, detectedLang)
      .then(lines => { if (lines?.length > 0) setDiarized(lines); })
      .catch(() => {})
      .finally(() => setDiarizing(false));
  }, [text]);

  // Use diarized lines (auto or stored), falling back to plain text
  const rawLines = storedLines || diarized;

  const langOpts = useMemo(() => {
    const opts = [{ key: 'original', label: 'Original' }];
    if (detectedLang !== 'en') opts.push({ key: 'en', label: 'EN' });
    if (detectedLang !== 'hi') opts.push({ key: 'hi', label: '\u0939\u093f\u0902' });
    return opts;
  }, [detectedLang]);

  const handleLang = async (lang) => {
    if (lang === selectedLang) return;
    setSelectedLang(lang);
    if (lang === 'original' || cache[lang]) return;
    setTranslating(true);
    try {
      const source = rawLines || [{ text }];
      const results = await Promise.all(source.map(l => translateTranscript(l.text, lang)));
      setCache(prev => ({ ...prev, [lang]: source.map((l, i) => ({ ...l, text: results[i] })) }));
    } catch {
      setSelectedLang('original');
    } finally {
      setTranslating(false);
    }
  };

  const activeLines = selectedLang === 'original'
    ? rawLines
    : (Array.isArray(cache[selectedLang]) ? cache[selectedLang] : rawLines);

  if (!text) return null;

  return (
    <View style={s.txCard}>
      <View style={s.txHeader}>
        <Text style={s.txLabel}>Transcript</Text>
        <View style={s.txLangRow}>
          {langOpts.map(opt => (
            <TouchableOpacity
              key={opt.key}
              style={[s.txLangPill, selectedLang === opt.key && s.txLangPillOn]}
              onPress={() => handleLang(opt.key)}
              disabled={translating}
              activeOpacity={0.75}
            >
              <Text style={[s.txLangTxt, selectedLang === opt.key && s.txLangTxtOn]}>
                {opt.label}
              </Text>
            </TouchableOpacity>
          ))}
          {translating && <ActivityIndicator size="small" color="#9333ea" style={{ marginLeft: 4 }} />}
        </View>
      </View>

      {diarizing && !activeLines && (
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 12 }}>
          <ActivityIndicator size="small" color={C.muted} />
          <Text style={{ fontSize: 13, fontFamily: 'SpaceGrotesk_400Regular', color: C.muted }}>
            Splitting speakers…
          </Text>
        </View>
      )}

      {activeLines ? (
        <View style={{ gap: 10 }}>
          {activeLines.map((line, i) => {
            if (line.speaker === 'noise' || !line.text?.trim()) return null;
            const isDoc = line.speaker === 'doctor' || !!line.name?.match(/^dr[\s.]/i);
            return (
              <View key={i} style={[s.msgOuter, { alignItems: isDoc ? 'flex-end' : 'flex-start' }]}>
                <View style={s.msgInner}>
                  {!isDoc && (
                    <View style={[s.msgAvatar, s.msgAvatarPat]}>
                      <Text style={s.msgAvatarTxt}>{(line.name || 'P')[0].toUpperCase()}</Text>
                    </View>
                  )}
                  <View style={[s.msgContent, isDoc && s.msgContentDoc]}>
                    {line.name && (
                      <Text style={[s.msgSpeaker, isDoc && s.msgSpeakerDoc]}>{line.name}</Text>
                    )}
                    <View style={[s.msgBubble, isDoc ? s.msgBubbleDoc : s.msgBubblePat]}>
                      <Text style={[s.msgBubbleTxt, isDoc && s.msgBubbleTxtDoc]}>{line.text}</Text>
                    </View>
                  </View>
                  {isDoc && (
                    <View style={[s.msgAvatar, s.msgAvatarDoc]}>
                      <Ionicons name="medical-outline" size={11} color="#ffffff" />
                    </View>
                  )}
                </View>
              </View>
            );
          })}
        </View>
      ) : !diarizing && (
        <Text style={s.txPlain}>{text}</Text>
      )}
    </View>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  scroll:    { paddingHorizontal: 20, paddingTop: 12 },

  backBtn:   { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 20 },
  backText:  { fontSize: 15, fontFamily: 'SpaceGrotesk_600SemiBold', color: C.dark },

  titleRow:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  titleBadges: { flexDirection: 'row', gap: 6 },
  pageTitle:   { fontSize: 26, fontFamily: 'SpaceGrotesk_700Bold', color: C.dark, letterSpacing: -0.5 },
  statusBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 50, paddingHorizontal: 12, paddingVertical: 5 },
  statusText:  { fontSize: 12, fontFamily: 'SpaceGrotesk_700Bold' },

  metaRow:  { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 20 },
  metaText: { fontSize: 12, fontFamily: 'SpaceGrotesk_400Regular', color: C.muted },
  metaDot:  { fontSize: 12, color: C.muted },

  summaryCard: { backgroundColor: C.dark, borderRadius: 20, padding: 18, marginBottom: 12 },
  summaryText: { fontSize: 15, fontFamily: 'SpaceGrotesk_400Regular', color: C.white, lineHeight: 22 },

  infoRow:   { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: C.white, borderRadius: 14, paddingHorizontal: 16, paddingVertical: 13, marginBottom: 8 },
  infoLabel: { fontSize: 13, fontFamily: 'SpaceGrotesk_500Medium', color: C.muted, width: 88 },
  infoValue: { flex: 1, fontSize: 14, fontFamily: 'SpaceGrotesk_600SemiBold', color: C.dark },

  sectionCard:   { backgroundColor: C.white, borderRadius: 18, padding: 16, marginBottom: 8, gap: 10 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle:  { fontSize: 12, fontFamily: 'SpaceGrotesk_700Bold', color: C.gray, textTransform: 'uppercase', letterSpacing: 0.8 },

  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip:     { backgroundColor: C.bg, borderRadius: 50, paddingHorizontal: 13, paddingVertical: 6 },
  chipText: { fontSize: 13, fontFamily: 'SpaceGrotesk_500Medium', color: C.dark },

  medCard:     { gap: 4 },
  medNameRow:  { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  medNameText: { fontSize: 15, fontFamily: 'SpaceGrotesk_700Bold', color: C.dark, flex: 1, marginBottom: 6 },
  medPillRow:  { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  medPill:     { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: C.bg, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4 },
  medPillText: { fontSize: 11, fontFamily: 'SpaceGrotesk_500Medium', color: C.gray },

  vitalsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  vitalTile:  { flex: 1, minWidth: 80, backgroundColor: C.bg, borderRadius: 14, padding: 14, alignItems: 'center', gap: 5 },
  vitalValue: { fontSize: 17, fontFamily: 'SpaceGrotesk_700Bold', color: C.dark },
  vitalLabel: { fontSize: 11, fontFamily: 'SpaceGrotesk_500Medium', color: C.gray, textAlign: 'center' },

  missingCard:  { backgroundColor: C.warn, borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#fcd34d', gap: 8, marginBottom: 8 },
  missingHeader:{ flexDirection: 'row', alignItems: 'center', gap: 8 },
  missingTitle: { fontSize: 13, fontFamily: 'SpaceGrotesk_700Bold', color: '#92400e', flex: 1 },
  missingRow:   { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
  missingText:  { fontSize: 13, fontFamily: 'SpaceGrotesk_500Medium', color: '#92400e', flex: 1, lineHeight: 19 },

  txCard:           { backgroundColor: C.white, borderRadius: 18, padding: 16, marginBottom: 8 },
  txHeader:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  txLabel:          { fontSize: 11, fontFamily: 'SpaceGrotesk_700Bold', color: C.gray, textTransform: 'uppercase', letterSpacing: 0.8 },
  txLangRow:        { flexDirection: 'row', alignItems: 'center', gap: 5 },
  txLangPill:       { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20, backgroundColor: C.bg, borderWidth: 1, borderColor: '#ddd' },
  txLangPillOn:     { backgroundColor: C.dark, borderColor: C.dark },
  txLangTxt:        { fontSize: 11, fontFamily: 'SpaceGrotesk_600SemiBold', color: C.gray },
  txLangTxtOn:      { color: C.white },
  txPlain:          { fontSize: 14, fontFamily: 'SpaceGrotesk_400Regular', color: C.dark, lineHeight: 22 },
  msgOuter:         { width: '100%' },
  msgInner:         { flexDirection: 'row', alignItems: 'flex-end', gap: 8, maxWidth: '85%' },
  msgAvatar:        { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  msgAvatarPat:     { backgroundColor: '#e8e8e8' },
  msgAvatarDoc:     { backgroundColor: C.dark },
  msgAvatarTxt:     { fontSize: 11, fontFamily: 'SpaceGrotesk_700Bold', color: C.dark },
  msgContent:       { flex: 1, gap: 2, alignItems: 'flex-start' },
  msgContentDoc:    { alignItems: 'flex-end' },
  msgSpeaker:       { fontSize: 10, fontFamily: 'SpaceGrotesk_600SemiBold', color: C.muted },
  msgSpeakerDoc:    { textAlign: 'right' },
  msgBubble:        { borderRadius: 14, paddingHorizontal: 13, paddingVertical: 9 },
  msgBubbleDoc:     { backgroundColor: C.dark, borderBottomRightRadius: 3 },
  msgBubblePat:     { backgroundColor: '#f0f0f2', borderBottomLeftRadius: 3 },
  msgBubbleTxt:     { fontSize: 14, fontFamily: 'SpaceGrotesk_400Regular', lineHeight: 21, color: C.dark },
  msgBubbleTxtDoc:  { color: C.white },

  rxBtn:      { backgroundColor: C.lime, borderRadius: 20, paddingHorizontal: 18, paddingVertical: 16, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  rxBtnInner: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  rxBtnTitle: { fontSize: 15, fontFamily: 'SpaceGrotesk_700Bold', color: C.dark },
  rxBtnSub:   { fontSize: 12, fontFamily: 'SpaceGrotesk_400Regular', color: '#3a6e00', marginTop: 2 },
});
